name: 'Write CSV'
description: 'Write output CSV files'
inputs:
  test-results:
    required: true
  output-sp-list-csv:
    required: true
  output-orgs-csv:
    required: true
  output-processed-csv:
    required: true
runs:
  using: 'node16'
  env:
    GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
  main: 'dist/index.js'
